# 配置名称
spring:
    application:
      name: SpringZuul
    rabbitmq:
      host: 192.168.99.100
      port: 5672
      username: SpringCloud
      password: SpringCloud123


# 配置端口
server:
  port: 4001

# 配置路由
zuul:
  routes:
    api-feign1:
      path: /api-f1/**
      serviceId: FeignServer

dev:
  config:
    desc: test123
