# 配置名称
spring:
    application:
      name: SpringZuul



# 配置端口
server:
  port: 4001

# 配置路由
zuul:
  routes:
    api-feign1:
      path: /api-f1/**
      serviceId: FeignServer

dev:
  config:
    desc: test123456
