# 配置名称
spring:
    application:
      name: SpringZuul

# 配置端口
server:
  port: 4001

# 配置注册中心
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:18090/eureka/

# 配置路由
zuul:
  routes:
    api-feign1:
      path: /api-f1/**
      serviceId: FeignServer


